title = "gitleaks config"

[allowlist]
description = "global allowlist"
paths = [
    '''test/fixtures''',
    '''.env''',
    '''node_modules''',
    '''dist''',
    '''build''',
    '''coverage''',
    '''tmp'''
]

[[rules]]
description = "Slack Bot Token"
id = "slack-bot-token"
regex = '''(xoxb-[0-9]{10,13}-[0-9]{10,13}-[a-zA-Z0-9]{24})'''
keywords = ["xoxb"]

[[rules]]
description = "Slack User Token"
id = "slack-user-token"
regex = '''(xoxp-[0-9]{10,13}-[0-9]{10,13}-[0-9]{10,13}-[a-zA-Z0-9]{24})'''
keywords = ["xoxp"]

[[rules]]
description = "Slack App Token"
id = "slack-app-token"
regex = '''(xapp-[0-9]{1,13}-[0-9]{1,13}-[a-zA-Z0-9]{24})'''
keywords = ["xapp"]
