#!/usr/bin/env node
// DevBox wrapper - use boxer's devbox

const { spawnSync } = require('child_process');
const args = process.argv.slice(2);

const boxerDevbox = '/home/alex/users/boxer/devbox/cli.js';
const result = spawnSync('node', [boxerDevbox, ...args], { stdio: 'inherit' });
process.exit(result.status || 0);
