service: vabamorf-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  
  environment:
    VMETAJSON_PATH: /var/task/vmetajson.bin
    DICT_PATH: /var/task
    AWS_LWA_PORT: 8080
    PORT: 8080

  ecr:
    images:
      vabamorf:
        path: ./

functions:
  api:
    image:
      name: vabamorf
    timeout: 30
    memorySize: 1024
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${self:custom.domainNames.${self:provider.stage}}
    certificateArn: arn:aws:acm:eu-west-1:465168436856:certificate/f91069e3-9ca9-4651-b912-765c9f49fc0d
    endpointType: REGIONAL
    apiType: http
    createRoute53Record: true
    hostedZoneId: Z08749823PH6RLXNTUZOF
  domainNames:
    dev: vabamorf-dev.askend-lab.com
    prod: vabamorf.askend-lab.com

resources:
  Outputs:
    ApiEndpoint:
      Description: Vabamorf API Gateway endpoint URL
      Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com
