/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
export default {
  packageManager: "pnpm",
  plugins: ["@stryker-mutator/vitest-runner"],
  reporters: ["clear-text", "progress", "json"],
  testRunner: "vitest",
  vitest: {
    configFile: "vitest.config.ts",
  },
  coverageAnalysis: "all",
  mutate: [
    "src/**/*.ts",
    "src/**/*.tsx",
    "!src/**/*.test.ts",
    "!src/**/*.test.tsx",
    "!src/test/**",
    "!src/features/**",
    "!src/main.tsx",
    "!src/vite-env.d.ts",
    "!src/types/**",
    "!src/services/__mocks__/**",
    "!src/services/specs/**",
    "!src/data/**",
    "!src/styles/**",
    "!src/utils/a11y-dev.ts",
    "!src/utils/warmAudioWorker.ts",
    "!src/services/storage/MockDataLoader.ts",
    "!src/services/auth/index.ts",
    "!src/services/auth/types.ts",
    "!src/**/*.generated.ts",
    "!src/utils/synthesize.ts",
    "!src/App.tsx",
    "!src/services/repository/TaskRepository.ts",
    "!src/hooks/useTaskHandlers.ts",
    "!src/components/TaskDetailView/TaskDetailView.tsx",
    "!src/components/TaskDetailView/hooks/usePronunciationVariants.ts",
    "!src/components/TaskDetailView/hooks/usePhoneticPanel.ts",
    "!src/pages/SharedTaskPage.tsx",
    "!src/components/SpecsPage.tsx",
    "!src/services/dataService.ts",
    "!src/services/storage/ShareService.ts",
  ],
  thresholds: {
    high: 80,
    low: 60,
    break: 50,
  },
  timeoutMS: 60000,
  concurrency: 4,
};
