export const TEXT_LIMITS = {
  MAX_AUDIO_TEXT_LENGTH: 1000,
  MAX_MORPHOLOGY_TEXT_LENGTH: 10000,
} as const;

export const TIMING = {
  POLL_INTERVAL_MS: 1000,
  ERROR_RETRY_DELAY_MS: 5000,
  NOTIFICATION_DURATION_MS: 5000,
} as const;
